
@baseUrl = http://localhost:3000/api/v1

### Lista todos os usuários
GET	{{baseUrl}}/users	

### Busca um usuário pelo ID/:id
GET	{{baseUrl}}/users/6/	

### Cria um novo usuário
POST {{baseUrl}}/users	
Content-Type: application/json

{
  "user": "Arllan Santana",
  "pass": "221601",
  "email": "arllan@gmail.com",
  "member": "avançado",
  "status": "ativo"
}

### Atualiza os dados de um usuário
PUT	{{baseUrl}}/users/1/	
Content-Type: application/json

{
  "user": "Francisco Pedro",
  "pass": "112233",
  "email": "francisco@gmail.com",
  "member": "supervisor",
  "status": "ativo"
}

###Remove um usuário
DELETE	{{baseUrl}}/users/19	

### Filtra usuários pelo status
GET	{{baseUrl}}/users/status/ativo	

### Filtra usuários pela função
GET	{{baseUrl}}/users/role/user